In [2]:
import os

PROJECT_DIR = "/path/to/kidney-rejection-project"  

RAW_DIR = os.path.join(PROJECT_DIR, "dataset", "raw")
PROCESSED_DIR = os.path.join(PROJECT_DIR, "dataset", "processed")

os.makedirs(RAW_DIR, exist_ok=True)
os.makedirs(PROCESSED_DIR, exist_ok=True)

print("Raw data dir:", RAW_DIR)
print("Processed data dir:", PROCESSED_DIR)

Raw data dir: /path/to/kidney-rejection-project/dataset/raw
Processed data dir: /path/to/kidney-rejection-project/dataset/processed

In [3]:
!pip install -q GEOparse combat scanpy pyarrow

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 42.5 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.8/188.8 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 92.5 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 94.2 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 MB 32.4 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.7/363.7 kB 19.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 113.7 MB/s eta 0:00:0000:0100:01
  Building wheel for combat (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
ydata-profiling 4.18.4 requires numba<0.63,>=0.60, but you have numba 0.67.0 which is incompatible.
ydata-profiling 4.18.4 requires numpy<2.4,>=1.22, but you have numpy 2.5.2 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.67.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.67.0 which is incompatible.

In [4]:
GEO_ACCESSIONS = [
    "GSE36059",
    "GSE21374",
    "GSE48581",
    "GSE98320",
]

RANDOM_SEED = 42
TRAIN_FRAC, VAL_FRAC, TEST_FRAC = 0.70, 0.15, 0.15

In [5]:
import GEOparse

gse_36059 = GEOparse.get_GEO(geo="GSE36059", destdir=RAW_DIR)
print("Samples in GSE36059:", len(gse_36059.gsms))
print("Platforms:", list(gse_36059.gpls.keys()))

05-Sep-2026 01:55:10 DEBUG utils - Directory /path/to/kidney-rejection-project/dataset/raw already exists. Skipping.
05-Sep-2026 01:55:10 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE36nnn/GSE36059/soft/GSE36059_family.soft.gz to /path/to/kidney-rejection-project/dataset/raw/GSE36059_family.soft.gz
100%|██████████| 194M/194M [00:03<00:00, 55.4MB/s]
05-Sep-2026 01:55:14 DEBUG downloader - Size validation passed
05-Sep-2026 01:55:14 DEBUG downloader - Moving /tmp/tmpo8h76y5j to /path/to/kidney-rejection-project/dataset/raw/GSE36059_family.soft.gz
05-Sep-2026 01:55:14 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE36nnn/GSE36059/soft/GSE36059_family.soft.gz
05-Sep-2026 01:55:14 INFO GEOparse - Parsing /path/to/kidney-rejection-project/dataset/raw/GSE36059_family.soft.gz:
05-Sep-2026 01:55:14 DEBUG GEOparse - DATABASE: GeoMiame
05-Sep-2026 01:55:14 DEBUG GEOparse - SERIES: GSE36059
05-Sep-2026 01:55:14 DEBUG GEOparse - PLATFORM: GPL570
/usr/local/lib/python3.12/dist-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
05-Sep-2026 01:55:16 DEBUG GEOparse - SAMPLE: GSM880204
05-Sep-2026 01:55:16 DEBUG GEOparse - SAMPLE: GSM880205
05-Sep-2026 01:55:16 DEBUG GEOparse - SAMPLE: GSM880206
05-Sep-2026 01:55:16 DEBUG GEOparse - SAMPLE: GSM880207
05-Sep-2026 01:55:16 DEBUG GEOparse - SAMPLE: GSM880208
05-Sep-2026 01:55:16 DEBUG GEOparse - SAMPLE: GSM880209
05-Sep-2026 01:55:16 DEBUG GEOparse - SAMPLE: GSM880210
05-Sep-2026 01:55:16 DEBUG GEOparse - SAMPLE: GSM880211
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880212
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880213
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880214
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880215
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880216
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880217
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880218
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880219
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880220
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880221
05-Sep-2026 01:55:17 DEBUG GEOparse - SAMPLE: GSM880222
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880223
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880224
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880225
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880226
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880227
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880228
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880229
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880230
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880231
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880232
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880233
05-Sep-2026 01:55:18 DEBUG GEOparse - SAMPLE: GSM880234
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880235
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880236
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880237
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880238
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880239
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880240
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880241
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880242
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880243
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880244
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880245
05-Sep-2026 01:55:19 DEBUG GEOparse - SAMPLE: GSM880246
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880247
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880248
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880249
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880250
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880251
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880252
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880253
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880254
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880255
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880256
05-Sep-2026 01:55:20 DEBUG GEOparse - SAMPLE: GSM880257
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880258
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880259
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880260
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880261
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880262
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880263
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880264
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880265
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880266
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880267
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880268
05-Sep-2026 01:55:21 DEBUG GEOparse - SAMPLE: GSM880269
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880270
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880271
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880272
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880273
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880274
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880275
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880276
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880277
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880278
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880279
05-Sep-2026 01:55:22 DEBUG GEOparse - SAMPLE: GSM880280
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880281
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880282
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880283
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880284
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880285
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880286
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880287
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880288
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880289
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880290
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880291
05-Sep-2026 01:55:23 DEBUG GEOparse - SAMPLE: GSM880292
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880293
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880294
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880295
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880296
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880297
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880298
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880299
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880300
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880301
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880302
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880303
05-Sep-2026 01:55:24 DEBUG GEOparse - SAMPLE: GSM880304
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880305
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880306
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880307
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880308
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880309
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880310
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880311
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880312
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880313
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880314
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880315
05-Sep-2026 01:55:25 DEBUG GEOparse - SAMPLE: GSM880316
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880317
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880318
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880319
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880320
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880321
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880322
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880323
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880324
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880325
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880326
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880327
05-Sep-2026 01:55:26 DEBUG GEOparse - SAMPLE: GSM880328
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880329
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880330
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880331
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880332
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880333
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880334
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880335
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880336
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880337
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880338
05-Sep-2026 01:55:27 DEBUG GEOparse - SAMPLE: GSM880339
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880340
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880341
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880342
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880343
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880344
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880345
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880346
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880347
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880348
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880349
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880350
05-Sep-2026 01:55:28 DEBUG GEOparse - SAMPLE: GSM880351
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880352
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880353
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880354
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880355
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880356
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880357
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880358
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880359
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880360
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880361
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880362
05-Sep-2026 01:55:29 DEBUG GEOparse - SAMPLE: GSM880363
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880364
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880365
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880366
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880367
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880368
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880369
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880370
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880371
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880372
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880373
05-Sep-2026 01:55:30 DEBUG GEOparse - SAMPLE: GSM880374
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880375
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880376
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880377
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880378
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880379
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880380
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880381
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880382
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880383
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880384
05-Sep-2026 01:55:31 DEBUG GEOparse - SAMPLE: GSM880385
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880386
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880387
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880388
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880389
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880390
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880391
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880392
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880393
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880394
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880395
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880396
05-Sep-2026 01:55:32 DEBUG GEOparse - SAMPLE: GSM880397
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880398
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880399
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880400
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880401
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880402
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880403
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880404
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880405
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880406
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880407
05-Sep-2026 01:55:33 DEBUG GEOparse - SAMPLE: GSM880408
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880409
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880410
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880411
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880412
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880413
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880414
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880415
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880416
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880417
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880418
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880419
05-Sep-2026 01:55:34 DEBUG GEOparse - SAMPLE: GSM880420
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880421
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880422
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880423
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880424
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880425
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880426
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880427
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880428
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880429
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880430
05-Sep-2026 01:55:35 DEBUG GEOparse - SAMPLE: GSM880431
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880432
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880433
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880434
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880435
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880436
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880437
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880438
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880439
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880440
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880441
05-Sep-2026 01:55:36 DEBUG GEOparse - SAMPLE: GSM880442
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880443
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880444
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880445
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880446
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880447
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880448
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880449
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880450
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880451
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880452
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880453
05-Sep-2026 01:55:37 DEBUG GEOparse - SAMPLE: GSM880454
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880455
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880456
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880457
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880458
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880459
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880460
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880461
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880462
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880463
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880464
05-Sep-2026 01:55:38 DEBUG GEOparse - SAMPLE: GSM880465
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880466
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880467
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880468
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880469
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880470
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880471
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880472
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880473
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880474
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880475
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880476
05-Sep-2026 01:55:39 DEBUG GEOparse - SAMPLE: GSM880477
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880478
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880479
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880480
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880481
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880482
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880483
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880484
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880485
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880486
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880487
05-Sep-2026 01:55:40 DEBUG GEOparse - SAMPLE: GSM880488
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880489
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880490
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880491
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880492
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880493
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880494
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880495
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880496
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880497
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880498
05-Sep-2026 01:55:41 DEBUG GEOparse - SAMPLE: GSM880499
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880500
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880501
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880502
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880503
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880504
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880505
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880506
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880507
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880508
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880509
05-Sep-2026 01:55:42 DEBUG GEOparse - SAMPLE: GSM880510
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880511
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880512
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880513
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880514
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880515
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880516
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880517
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880518
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880519
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880520
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880521
05-Sep-2026 01:55:43 DEBUG GEOparse - SAMPLE: GSM880522
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880523
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880524
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880525
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880526
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880527
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880528
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880529
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880530
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880531
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880532
05-Sep-2026 01:55:44 DEBUG GEOparse - SAMPLE: GSM880533
05-Sep-2026 01:55:45 DEBUG GEOparse - SAMPLE: GSM880534
05-Sep-2026 01:55:45 DEBUG GEOparse - SAMPLE: GSM880535
05-Sep-2026 01:55:45 DEBUG GEOparse - SAMPLE: GSM880536
05-Sep-2026 01:55:45 DEBUG GEOparse - SAMPLE: GSM880537
05-Sep-2026 01:55:45 DEBUG GEOparse - SAMPLE: GSM880538

Samples in GSE36059: 411
Platforms: ['GPL570']

In [6]:
for i, (gsm_name, gsm) in enumerate(gse_36059.gsms.items()):
    if i >= 8:
        break
    print(gsm_name, "->", gsm.metadata.get("characteristics_ch1", []))

GSM880204 -> ['diagnosis (tcmr,abmr,mixed,non-rejecting): non-rejecting', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM880205 -> ['diagnosis (tcmr,abmr,mixed,non-rejecting): non-rejecting', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Borderline', 'ah-lesion score (0, >0): 0']
GSM880206 -> ['diagnosis (tcmr,abmr,mixed,non-rejecting): non-rejecting', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM880207 -> ['diagnosis (tcmr,abmr,mixed,non-rejecting): non-rejecting', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM880208 -> ['diagnosis (tcmr,abmr,mixed,non-rejecting): non-rejecting', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM880209 -> ['diagnosis (tcmr,abmr,mixed,non-rejecting): non-rejecting', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM880210 -> ['diagnosis (tcmr,abmr,mixed,non-rejecting): non-rejecting', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM880211 -> ['diagnosis (tcmr,abmr,mixed,non-rejecting): non-rejecting', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']

In [7]:
import pandas as pd
import re

def extract_characteristics(gsm):
    """Turn a GSM's characteristics_ch1 list into a dict of {field: value}."""
    out = {}
    for entry in gsm.metadata.get("characteristics_ch1", []):
        if ":" in entry:
            key, val = entry.split(":", 1)
            out[key.strip()] = val.strip()
    return out

rows = []
for gsm_name, gsm in gse_36059.gsms.items():
    chars = extract_characteristics(gsm)
    chars["sample_id"] = gsm_name
    rows.append(chars)

meta_36059 = pd.DataFrame(rows).set_index("sample_id")
print(meta_36059.columns.tolist())
meta_36059.head()

['diagnosis (tcmr,abmr,mixed,non-rejecting)', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others)', 'ah-lesion score (0, >0)']

,"diagnosis (tcmr,abmr,mixed,non-rejecting)","histologic diagnosis (abmr, tcmr, bdl, mixed, others)","ah-lesion score (0, >0)"
sample_id,,,
GSM880204,non-rejecting,Others,>0
GSM880205,non-rejecting,Borderline,0
GSM880206,non-rejecting,Others,>0
GSM880207,non-rejecting,Others,>0
GSM880208,non-rejecting,Others,>0

In [8]:
DIAGNOSIS_COL = "diagnosis (tcmr,abmr,mixed,non-rejecting)"

LABEL_MAP_36059 = {
    "non-rejecting": "NR",
    "tcmr": "TCMR",
    "abmr": "ABMR",
    "mixed": "Mixed",
}

meta_36059["rejection_class"] = (
    meta_36059[DIAGNOSIS_COL].str.lower().str.strip().map(LABEL_MAP_36059)
)

print(meta_36059["rejection_class"].value_counts(dropna=False))

rejection_class
NR       281
ABMR      65
TCMR      35
Mixed     22
NaN        8
Name: count, dtype: int64

In [9]:
nan_rows = meta_36059[meta_36059["rejection_class"].isna()]
print(nan_rows[DIAGNOSIS_COL].unique())
nan_rows[[DIAGNOSIS_COL]]

['Nephrectomy']

          diagnosis (tcmr,abmr,mixed,non-rejecting)
sample_id
GSM880245                               Nephrectomy
GSM880246                               Nephrectomy
GSM880299                               Nephrectomy
GSM880311                               Nephrectomy
GSM880318                               Nephrectomy
GSM880430                               Nephrectomy
GSM880447                               Nephrectomy
GSM880500                               Nephrectomy

In [10]:
meta_36059_clean = meta_36059.dropna(subset=["rejection_class"]).copy()

print(f"Dropped {len(meta_36059) - len(meta_36059_clean)} non-transplant/unlabeled samples")
print(f"Final GSE36059 labeled samples: {len(meta_36059_clean)}")
print(meta_36059_clean["rejection_class"].value_counts())

Dropped 8 non-transplant/unlabeled samples
Final GSE36059 labeled samples: 403
rejection_class
NR       281
ABMR      65
TCMR      35
Mixed     22
Name: count, dtype: int64

In [11]:
expr_frames = []
for gsm_name in meta_36059_clean.index:
    gsm = gse_36059.gsms[gsm_name]
    if gsm.table is None or gsm.table.empty:
        continue
    series = gsm.table.set_index("ID_REF")["VALUE"]
    series.name = gsm_name
    expr_frames.append(series)

expr_36059 = pd.concat(expr_frames, axis=1)
print("Expression matrix shape (probes x samples):", expr_36059.shape)
expr_36059.head()

Expression matrix shape (probes x samples): (54675, 403)

,GSM880204,GSM880205,GSM880206,GSM880207,GSM880208,GSM880209,GSM880210,GSM880211,GSM880212,GSM880213,...,GSM880605,GSM880606,GSM880607,GSM880608,GSM880609,GSM880610,GSM880611,GSM880612,GSM880613,GSM880614
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,9.808114,10.682125,9.659079,10.083274,10.460354,9.908205,9.826789,9.849271,10.167985,9.479723,...,10.045520,10.185048,10.476428,9.915969,10.165729,9.934819,10.331492,10.434603,10.172647,9.717351
1053_at,6.039012,6.608906,6.025781,6.254128,6.304075,6.371497,6.350107,6.274171,6.061814,6.529935,...,7.250703,6.156028,6.621311,6.652392,6.324376,5.786077,6.694437,6.764096,6.226061,6.889039
117_at,5.810846,5.847419,6.089887,5.386257,5.550745,5.461051,6.057075,5.499230,5.508480,5.989576,...,5.787078,5.822168,6.196529,5.509276,5.442660,5.567057,5.935698,6.189874,5.550959,6.058230
121_at,10.342781,10.667633,10.385927,10.383023,11.367598,10.529191,10.540292,10.331817,10.715556,9.853745,...,9.845058,10.692428,10.321942,10.380285,10.776776,10.392874,10.768941,10.814140,10.757275,10.178743
1255_g_at,3.211123,2.924908,3.191762,3.096177,3.059629,3.138675,3.121389,3.021544,3.175132,3.229619,...,3.172923,3.017899,3.414540,3.151017,3.025866,3.156632,3.277184,3.115665,3.154218,3.126419

In [12]:
platform_ids = list(gse_36059.gpls.keys())
print("Platform(s):", platform_ids)

gpl = gse_36059.gpls[platform_ids[0]]
anno = gpl.table
print("Annotation columns:", anno.columns.tolist())
anno.head()

Platform(s): ['GPL570']
Annotation columns: ['ID', 'GB_ACC', 'SPOT_ID', 'Species Scientific Name', 'Annotation Date', 'Sequence Type', 'Sequence Source', 'Target Description', 'Representative Public ID', 'Gene Title', 'Gene Symbol', 'ENTREZ_GENE_ID', 'RefSeq Transcript ID', 'Gene Ontology Biological Process', 'Gene Ontology Cellular Component', 'Gene Ontology Molecular Function']

,ID,GB_ACC,SPOT_ID,Species Scientific Name,Annotation Date,Sequence Type,Sequence Source,Target Description,Representative Public ID,Gene Title,Gene Symbol,ENTREZ_GENE_ID,RefSeq Transcript ID,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function
0,1007_s_at,U48705,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,U48705 /FEATURE=mRNA /DEFINITION=HSU48705 Huma...,U48705,discoidin domain receptor tyrosine kinase 1 //...,DDR1 /// MIR4640,780 /// 100616237,NM_001202521 /// NM_001202522 /// NM_001202523...,0001558 // regulation of cell growth // inferr...,0005576 // extracellular region // inferred fr...,0000166 // nucleotide binding // inferred from...
1,1053_at,M87338,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,M87338 /FEATURE= /DEFINITION=HUMA1SBU Human re...,M87338,"replication factor C (activator 1) 2, 40kDa",RFC2,5982,NM_001278791 /// NM_001278792 /// NM_001278793...,0000278 // mitotic cell cycle // traceable aut...,0005634 // nucleus // inferred from electronic...,0000166 // nucleotide binding // inferred from...
2,117_at,X51757,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X51757 /FEATURE=cds /DEFINITION=HSP70B Human h...,X51757,heat shock 70kDa protein 6 (HSP70B'),HSPA6,3310,NM_002155,0000902 // cell morphogenesis // inferred from...,0005737 // cytoplasm // inferred from direct a...,0000166 // nucleotide binding // inferred from...
3,121_at,X69699,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,X69699 /FEATURE= /DEFINITION=HSPAX8A H.sapiens...,X69699,paired box 8,PAX8,7849,NM_003466 /// NM_013951 /// NM_013952 /// NM_0...,0001655 // urogenital system development // in...,0005634 // nucleus // inferred from direct ass...,0000979 // RNA polymerase II core promoter seq...
4,1255_g_at,L36861,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,L36861 /FEATURE=expanded_cds /DEFINITION=HUMGC...,L36861,guanylate cyclase activator 1A (retina),GUCA1A,2978,NM_000409 /// XM_006715073,0007165 // signal transduction // non-traceabl...,0001750 // photoreceptor outer segment // infe...,0005509 // calcium ion binding // inferred fro...

In [13]:
probe_to_gene = anno.set_index("ID")["Gene Symbol"]

expr_36059_genes = expr_36059.join(probe_to_gene.rename("gene_symbol"), how="left")

# Drop probes with no gene symbol (control probes, unannotated, etc.)
before = len(expr_36059_genes)
expr_36059_genes = expr_36059_genes.dropna(subset=["gene_symbol"])
expr_36059_genes = expr_36059_genes[expr_36059_genes["gene_symbol"].str.strip() != ""]
print(f"Dropped {before - len(expr_36059_genes)} unannotated/control probes")

# Multiple probes can map to the same gene (common on Affy arrays) —
# collapse by taking the mean expression across probes per gene
expr_36059_final = expr_36059_genes.groupby("gene_symbol").mean(numeric_only=True)

print("Gene-level expression matrix shape (genes x samples):", expr_36059_final.shape)
expr_36059_final.head()

Dropped 8893 unannotated/control probes
Gene-level expression matrix shape (genes x samples): (23520, 403)

,GSM880204,GSM880205,GSM880206,GSM880207,GSM880208,GSM880209,GSM880210,GSM880211,GSM880212,GSM880213,...,GSM880605,GSM880606,GSM880607,GSM880608,GSM880609,GSM880610,GSM880611,GSM880612,GSM880613,GSM880614
gene_symbol,,,,,,,,,,,,,,,,,,,,,
A1BG,4.463362,4.839094,4.714325,4.595232,4.556762,4.325320,4.378816,4.032678,4.250186,4.702101,...,4.704357,4.139483,4.659260,4.095436,4.127955,4.542668,4.928359,4.723794,4.429876,5.189572
A1BG-AS1,4.722304,4.653082,4.611039,4.528320,4.415328,4.215343,4.859253,4.420489,4.428422,4.844569,...,4.413751,4.379398,4.824622,4.541092,4.449386,4.762557,4.709455,4.387822,4.536987,4.686436
A1CF,8.315396,6.068552,8.074610,7.052072,4.611542,8.377363,8.563437,8.613024,8.393399,6.994819,...,7.210120,7.816004,6.622216,7.865570,8.771730,8.352315,5.956107,6.238520,7.714769,5.552046
A2M,8.178305,8.329760,8.115036,8.104079,8.332045,8.160087,8.488747,7.889960,8.156051,7.894072,...,8.403257,8.583575,8.461699,8.289582,7.856059,8.209941,8.216301,8.603457,8.236612,8.491542
A2M-AS1,5.485448,6.242896,5.254115,5.773315,5.673816,6.152899,5.126477,6.015067,4.961952,4.798648,...,5.901956,6.529469,5.591717,5.342055,5.450019,4.839142,5.594139,6.084748,5.962374,6.043555

In [14]:
common_samples = expr_36059_final.columns.intersection(meta_36059_clean.index)
print(f"Samples in expression matrix: {expr_36059_final.shape[1]}")
print(f"Samples in metadata: {len(meta_36059_clean)}")
print(f"Common samples: {len(common_samples)}")

expr_36059_final = expr_36059_final[common_samples]
meta_36059_clean = meta_36059_clean.loc[common_samples]

assert (expr_36059_final.columns == meta_36059_clean.index).all()
print("Aligned successfully:", expr_36059_final.shape[1], "samples")

Samples in expression matrix: 403
Samples in metadata: 403
Common samples: 403
Aligned successfully: 403 samples

In [15]:
import os

expr_36059_final.to_parquet(os.path.join(PROCESSED_DIR, "GSE36059_expression.parquet"))
meta_36059_clean.to_parquet(os.path.join(PROCESSED_DIR, "GSE36059_metadata.parquet"))

print("Saved:")
print(" -", os.path.join(PROCESSED_DIR, "GSE36059_expression.parquet"), expr_36059_final.shape)
print(" -", os.path.join(PROCESSED_DIR, "GSE36059_metadata.parquet"), meta_36059_clean.shape)

Saved:
 - /path/to/kidney-rejection-project/dataset/processed/GSE36059_expression.parquet (23520, 403)
 - /path/to/kidney-rejection-project/dataset/processed/GSE36059_metadata.parquet (403, 4)

In [16]:
gse_21374 = GEOparse.get_GEO(geo="GSE21374", destdir=RAW_DIR)
print("Samples in GSE21374:", len(gse_21374.gsms))
print("Platforms:", list(gse_21374.gpls.keys()))

05-Sep-2026 01:55:56 DEBUG utils - Directory /path/to/kidney-rejection-project/dataset/raw already exists. Skipping.
05-Sep-2026 01:55:56 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE21nnn/GSE21374/soft/GSE21374_family.soft.gz to /path/to/kidney-rejection-project/dataset/raw/GSE21374_family.soft.gz
100%|██████████| 137M/137M [00:02<00:00, 53.8MB/s]
05-Sep-2026 01:55:59 DEBUG downloader - Size validation passed
05-Sep-2026 01:55:59 DEBUG downloader - Moving /tmp/tmpxt8idgcr to /path/to/kidney-rejection-project/dataset/raw/GSE21374_family.soft.gz
05-Sep-2026 01:55:59 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE21nnn/GSE21374/soft/GSE21374_family.soft.gz
05-Sep-2026 01:55:59 INFO GEOparse - Parsing /path/to/kidney-rejection-project/dataset/raw/GSE21374_family.soft.gz:
05-Sep-2026 01:55:59 DEBUG GEOparse - DATABASE: GeoMiame
05-Sep-2026 01:55:59 DEBUG GEOparse - SERIES: GSE21374
05-Sep-2026 01:55:59 DEBUG GEOparse - PLATFORM: GPL570
/usr/local/lib/python3.12/dist-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533921
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533922
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533923
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533924
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533925
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533926
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533927
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533928
05-Sep-2026 01:56:01 DEBUG GEOparse - SAMPLE: GSM533929
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533930
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533931
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533932
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533933
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533934
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533935
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533936
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533937
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533938
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533939
05-Sep-2026 01:56:02 DEBUG GEOparse - SAMPLE: GSM533940
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533941
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533942
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533943
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533944
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533945
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533946
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533947
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533948
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533949
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533950
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533951
05-Sep-2026 01:56:03 DEBUG GEOparse - SAMPLE: GSM533952
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533953
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533954
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533955
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533956
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533957
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533958
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533959
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533960
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533961
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533962
05-Sep-2026 01:56:04 DEBUG GEOparse - SAMPLE: GSM533963
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533964
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533965
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533966
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533967
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533968
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533969
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533970
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533971
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533972
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533973
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533974
05-Sep-2026 01:56:05 DEBUG GEOparse - SAMPLE: GSM533975
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533976
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533977
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533978
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533979
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533980
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533981
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533982
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533983
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533984
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533985
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533986
05-Sep-2026 01:56:06 DEBUG GEOparse - SAMPLE: GSM533987
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533988
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533989
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533990
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533991
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533992
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533993
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533994
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533995
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533996
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533997
05-Sep-2026 01:56:07 DEBUG GEOparse - SAMPLE: GSM533998
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM533999
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534000
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534001
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534002
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534003
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534004
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534005
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534006
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534007
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534008
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534009
05-Sep-2026 01:56:08 DEBUG GEOparse - SAMPLE: GSM534010
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534011
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534012
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534013
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534014
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534015
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534016
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534017
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534018
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534019
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534020
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534021
05-Sep-2026 01:56:09 DEBUG GEOparse - SAMPLE: GSM534022
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534023
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534024
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534025
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534026
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534027
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534028
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534029
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534030
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534031
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534032
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534033
05-Sep-2026 01:56:10 DEBUG GEOparse - SAMPLE: GSM534034
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534035
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534036
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534037
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534038
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534039
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534040
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534041
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534042
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534043
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534044
05-Sep-2026 01:56:11 DEBUG GEOparse - SAMPLE: GSM534045
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534046
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534047
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534048
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534049
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534050
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534051
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534052
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534053
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534054
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534055
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534056
05-Sep-2026 01:56:12 DEBUG GEOparse - SAMPLE: GSM534057
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534058
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534059
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534060
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534061
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534062
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534063
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534064
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534065
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534066
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534067
05-Sep-2026 01:56:13 DEBUG GEOparse - SAMPLE: GSM534068
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534069
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534070
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534071
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534072
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534073
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534074
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534075
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534076
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534077
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534078
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534079
05-Sep-2026 01:56:14 DEBUG GEOparse - SAMPLE: GSM534080
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534081
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534082
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534083
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534084
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534085
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534086
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534087
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534088
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534089
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534090
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534091
05-Sep-2026 01:56:15 DEBUG GEOparse - SAMPLE: GSM534092
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534093
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534094
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534095
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534096
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534097
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534098
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534099
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534100
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534101
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534102
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534103
05-Sep-2026 01:56:16 DEBUG GEOparse - SAMPLE: GSM534104
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534105
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534106
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534107
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534108
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534109
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534110
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534111
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534112
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534113
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534114
05-Sep-2026 01:56:17 DEBUG GEOparse - SAMPLE: GSM534115
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534116
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534117
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534118
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534119
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534120
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534121
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534122
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534123
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534124
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534125
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534126
05-Sep-2026 01:56:18 DEBUG GEOparse - SAMPLE: GSM534127
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534128
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534129
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534130
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534131
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534132
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534133
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534134
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534135
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534136
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534137
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534138
05-Sep-2026 01:56:19 DEBUG GEOparse - SAMPLE: GSM534139
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534140
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534141
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534142
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534143
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534144
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534145
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534146
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534147
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534148
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534149
05-Sep-2026 01:56:20 DEBUG GEOparse - SAMPLE: GSM534150
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534151
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534152
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534153
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534154
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534155
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534156
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534157
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534158
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534159
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534160
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534161
05-Sep-2026 01:56:21 DEBUG GEOparse - SAMPLE: GSM534162
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534163
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534164
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534165
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534166
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534167
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534168
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534169
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534170
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534171
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534172
05-Sep-2026 01:56:22 DEBUG GEOparse - SAMPLE: GSM534173
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534174
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534175
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534176
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534177
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534178
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534179
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534180
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534181
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534182
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534183
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534184
05-Sep-2026 01:56:23 DEBUG GEOparse - SAMPLE: GSM534185
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534186
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534187
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534188
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534189
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534190
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534191
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534192
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534193
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534194
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534195
05-Sep-2026 01:56:24 DEBUG GEOparse - SAMPLE: GSM534196
05-Sep-2026 01:56:25 DEBUG GEOparse - SAMPLE: GSM534197
05-Sep-2026 01:56:25 DEBUG GEOparse - SAMPLE: GSM534198
05-Sep-2026 01:56:25 DEBUG GEOparse - SAMPLE: GSM534199
05-Sep-2026 01:56:25 DEBUG GEOparse - SAMPLE: GSM534200
05-Sep-2026 01:56:25 DEBUG GEOparse - SAMPLE: GSM534201
05-Sep-2026 01:56:25 DEBUG GEOparse - SAMPLE: GSM534202

Samples in GSE21374: 282
Platforms: ['GPL570']

In [17]:
for i, (gsm_name, gsm) in enumerate(gse_21374.gsms.items()):
    if i >= 8:
        break
    print(gsm_name, "->", gsm.metadata.get("characteristics_ch1", []))

GSM533921 -> ['failed=1/non failed=0: 0', 'time of biopsy post transplant (days): 277', 'time from biopsy to failure/censoring (days): 1084', 'rejection/non rejection: nonrej', 'sample included in the main analysis- the first biopsy per patient from the 105 late (> 1 year) patients: 0']
GSM533922 -> ['failed=1/non failed=0: 0', 'time of biopsy post transplant (days): 134', 'time from biopsy to failure/censoring (days): 1170', 'rejection/non rejection: nonrej', 'sample included in the main analysis- the first biopsy per patient from the 105 late (> 1 year) patients: 0']
GSM533923 -> ['failed=1/non failed=0: 1', 'time of biopsy post transplant (days): 795', 'time from biopsy to failure/censoring (days): 127', 'rejection/non rejection: nonrej', 'sample included in the main analysis- the first biopsy per patient from the 105 late (> 1 year) patients: 1']
GSM533924 -> ['failed=1/non failed=0: 0', 'time of biopsy post transplant (days): 2358', 'time from biopsy to failure/censoring (days): 1430', 'rejection/non rejection: nonrej', 'sample included in the main analysis- the first biopsy per patient from the 105 late (> 1 year) patients: 1']
GSM533925 -> ['failed=1/non failed=0: 0', 'time of biopsy post transplant (days): 64', 'time from biopsy to failure/censoring (days): 1244', 'rejection/non rejection: nonrej', 'sample included in the main analysis- the first biopsy per patient from the 105 late (> 1 year) patients: 0']
GSM533926 -> ['failed=1/non failed=0: 0', 'time of biopsy post transplant (days): 8', 'time from biopsy to failure/censoring (days): 1154', 'rejection/non rejection: rej', 'sample included in the main analysis- the first biopsy per patient from the 105 late (> 1 year) patients: 0']
GSM533927 -> ['failed=1/non failed=0: 0', 'time of biopsy post transplant (days): 745', 'time from biopsy to failure/censoring (days): 1410', 'rejection/non rejection: rej', 'sample included in the main analysis- the first biopsy per patient from the 105 late (> 1 year) patients: 1']
GSM533928 -> ['failed=1/non failed=0: 0', 'time of biopsy post transplant (days): 1309', 'time from biopsy to failure/censoring (days): 1254', 'rejection/non rejection: nonrej', 'sample included in the main analysis- the first biopsy per patient from the 105 late (> 1 year) patients: 1']

In [18]:
gse_48581 = GEOparse.get_GEO(geo="GSE48581", destdir=RAW_DIR)
print("Samples in GSE48581:", len(gse_48581.gsms))
print("Platforms:", list(gse_48581.gpls.keys()))

05-Sep-2026 02:01:39 DEBUG utils - Directory /path/to/kidney-rejection-project/dataset/raw already exists. Skipping.
05-Sep-2026 02:01:39 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE48nnn/GSE48581/soft/GSE48581_family.soft.gz to /path/to/kidney-rejection-project/dataset/raw/GSE48581_family.soft.gz
100%|██████████| 148M/148M [00:03<00:00, 42.2MB/s]
05-Sep-2026 02:01:44 DEBUG downloader - Size validation passed
05-Sep-2026 02:01:44 DEBUG downloader - Moving /tmp/tmpy7q5no82 to /path/to/kidney-rejection-project/dataset/raw/GSE48581_family.soft.gz
05-Sep-2026 02:01:44 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE48nnn/GSE48581/soft/GSE48581_family.soft.gz
05-Sep-2026 02:01:44 INFO GEOparse - Parsing /path/to/kidney-rejection-project/dataset/raw/GSE48581_family.soft.gz:
05-Sep-2026 02:01:44 DEBUG GEOparse - DATABASE: GeoMiame
05-Sep-2026 02:01:44 DEBUG GEOparse - SERIES: GSE48581
05-Sep-2026 02:01:44 DEBUG GEOparse - PLATFORM: GPL570
/usr/local/lib/python3.12/dist-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
05-Sep-2026 02:01:45 DEBUG GEOparse - SAMPLE: GSM1181496
05-Sep-2026 02:01:45 DEBUG GEOparse - SAMPLE: GSM1181497
05-Sep-2026 02:01:45 DEBUG GEOparse - SAMPLE: GSM1181498
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181499
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181500
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181501
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181502
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181503
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181504
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181505
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181506
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181507
05-Sep-2026 02:01:46 DEBUG GEOparse - SAMPLE: GSM1181508
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181509
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181510
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181511
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181512
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181513
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181514
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181515
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181516
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181517
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181518
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181519
05-Sep-2026 02:01:47 DEBUG GEOparse - SAMPLE: GSM1181520
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181521
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181522
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181523
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181524
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181525
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181526
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181527
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181528
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181529
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181530
05-Sep-2026 02:01:48 DEBUG GEOparse - SAMPLE: GSM1181531
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181532
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181533
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181534
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181535
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181536
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181537
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181538
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181539
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181540
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181541
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181542
05-Sep-2026 02:01:49 DEBUG GEOparse - SAMPLE: GSM1181543
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181544
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181545
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181546
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181547
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181548
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181549
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181550
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181551
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181552
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181553
05-Sep-2026 02:01:50 DEBUG GEOparse - SAMPLE: GSM1181554
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181555
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181556
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181557
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181558
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181559
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181560
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181561
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181562
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181563
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181564
05-Sep-2026 02:01:51 DEBUG GEOparse - SAMPLE: GSM1181565
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181566
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181567
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181568
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181569
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181570
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181571
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181572
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181573
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181574
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181575
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181576
05-Sep-2026 02:01:52 DEBUG GEOparse - SAMPLE: GSM1181577
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181578
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181580
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181582
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181584
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181586
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181588
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181590
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181591
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181592
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181593
05-Sep-2026 02:01:53 DEBUG GEOparse - SAMPLE: GSM1181594
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181595
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181596
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181597
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181598
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181599
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181600
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181601
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181602
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181603
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181604
05-Sep-2026 02:01:54 DEBUG GEOparse - SAMPLE: GSM1181605
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181606
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181607
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181608
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181609
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181610
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181611
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181612
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181613
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181614
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181615
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181616
05-Sep-2026 02:01:55 DEBUG GEOparse - SAMPLE: GSM1181617
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181618
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181619
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181620
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181621
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181622
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181623
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181624
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181625
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181626
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181627
05-Sep-2026 02:01:56 DEBUG GEOparse - SAMPLE: GSM1181628
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181629
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181630
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181631
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181632
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181633
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181634
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181635
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181636
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181637
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181638
05-Sep-2026 02:01:57 DEBUG GEOparse - SAMPLE: GSM1181639
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181640
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181641
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181643
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181644
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181645
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181648
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181651
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181653
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181654
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181656
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181658
05-Sep-2026 02:01:58 DEBUG GEOparse - SAMPLE: GSM1181660
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181661
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181662
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181663
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181664
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181665
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181666
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181667
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181668
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181669
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181670
05-Sep-2026 02:01:59 DEBUG GEOparse - SAMPLE: GSM1181671
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181672
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181673
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181674
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181675
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181676
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181677
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181678
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181679
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181680
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181681
05-Sep-2026 02:02:00 DEBUG GEOparse - SAMPLE: GSM1181682
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181683
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181684
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181685
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181686
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181687
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181688
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181689
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181690
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181691
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181692
05-Sep-2026 02:02:01 DEBUG GEOparse - SAMPLE: GSM1181693
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181694
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181695
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181696
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181697
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181698
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181699
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181700
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181701
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181702
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181703
05-Sep-2026 02:02:02 DEBUG GEOparse - SAMPLE: GSM1181704
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181705
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181706
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181707
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181708
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181709
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181710
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181711
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181712
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181713
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181714
05-Sep-2026 02:02:03 DEBUG GEOparse - SAMPLE: GSM1181715
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181716
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181717
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181718
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181719
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181720
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181721
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181722
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181723
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181724
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181725
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181726
05-Sep-2026 02:02:04 DEBUG GEOparse - SAMPLE: GSM1181727
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181728
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181729
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181730
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181731
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181732
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181733
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181734
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181735
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181736
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181737
05-Sep-2026 02:02:05 DEBUG GEOparse - SAMPLE: GSM1181738
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181739
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181740
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181741
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181742
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181743
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181744
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181745
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181746
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181747
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181748
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181749
05-Sep-2026 02:02:06 DEBUG GEOparse - SAMPLE: GSM1181750
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181751
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181752
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181753
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181754
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181755
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181756
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181757
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181758
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181759
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181760
05-Sep-2026 02:02:07 DEBUG GEOparse - SAMPLE: GSM1181761
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181762
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181763
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181764
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181765
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181766
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181767
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181768
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181769
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181770
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181771
05-Sep-2026 02:02:08 DEBUG GEOparse - SAMPLE: GSM1181772
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181773
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181774
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181775
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181776
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181777
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181778
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181779
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181780
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181781
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181782
05-Sep-2026 02:02:09 DEBUG GEOparse - SAMPLE: GSM1181783
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181784
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181785
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181786
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181787
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181788
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181789
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181790
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181791
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181792
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181793
05-Sep-2026 02:02:10 DEBUG GEOparse - SAMPLE: GSM1181794
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181795
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181796
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181797
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181798
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181799
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181800
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181801
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181802
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181803
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181804
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181805
05-Sep-2026 02:02:11 DEBUG GEOparse - SAMPLE: GSM1181806
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181807
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181808
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181809
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181810
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181811
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181812
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181813
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181814
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181815
05-Sep-2026 02:02:12 DEBUG GEOparse - SAMPLE: GSM1181816

Samples in GSE48581: 306
Platforms: ['GPL570']

In [19]:
for i, (gsm_name, gsm) in enumerate(gse_48581.gsms.items()):
    if i >= 8:
        break
    print(gsm_name, "->", gsm.metadata.get("characteristics_ch1", []))

GSM1181496 -> ['tissue: renal allograft biopsy', 'diagnosis (tcmr,non-tcmr, nephrectomies): non-TCMR', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM1181497 -> ['tissue: renal allograft biopsy', 'diagnosis (tcmr,non-tcmr, nephrectomies): non-TCMR', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): 0']
GSM1181498 -> ['tissue: renal allograft biopsy', 'diagnosis (tcmr,non-tcmr, nephrectomies): non-TCMR', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM1181499 -> ['tissue: renal allograft biopsy', 'diagnosis (tcmr,non-tcmr, nephrectomies): non-TCMR', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM1181500 -> ['tissue: renal allograft biopsy', 'diagnosis (tcmr,non-tcmr, nephrectomies): non-TCMR', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): 0']
GSM1181501 -> ['tissue: renal allograft biopsy', 'diagnosis (tcmr,non-tcmr, nephrectomies): non-TCMR', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): ABMR', 'ah-lesion score (0, >0): 0']
GSM1181502 -> ['tissue: renal allograft biopsy', 'diagnosis (tcmr,non-tcmr, nephrectomies): non-TCMR', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): Others', 'ah-lesion score (0, >0): >0']
GSM1181503 -> ['tissue: renal allograft biopsy', 'diagnosis (tcmr,non-tcmr, nephrectomies): non-TCMR', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others): ABMR', 'ah-lesion score (0, >0): >0']

In [20]:
rows = []
for gsm_name, gsm in gse_48581.gsms.items():
    chars = extract_characteristics(gsm)
    chars["sample_id"] = gsm_name
    rows.append(chars)

meta_48581 = pd.DataFrame(rows).set_index("sample_id")
print(meta_48581.columns.tolist())

HIST_COL = "histologic diagnosis (abmr, tcmr, bdl, mixed, others)"
COARSE_COL = "diagnosis (tcmr,non-tcmr, nephrectomies)"

print("\nHistologic diagnosis counts:")
print(meta_48581[HIST_COL].value_counts(dropna=False))

print("\nCross-tab: histologic vs coarse diagnosis:")
print(pd.crosstab(meta_48581[HIST_COL], meta_48581[COARSE_COL]))

['tissue', 'diagnosis (tcmr,non-tcmr, nephrectomies)', 'histologic diagnosis (abmr, tcmr, bdl, mixed, others)', 'ah-lesion score (0, >0)']

Histologic diagnosis counts:
histologic diagnosis (abmr, tcmr, bdl, mixed, others)
Others        151
NA             48
Borderline     42
ABMR           32
TCMR           29
Mixed           4
Name: count, dtype: int64

Cross-tab: histologic vs coarse diagnosis:
diagnosis (tcmr,non-tcmr, nephrectomies)            Nephrectomies  TCMR  \
histologic diagnosis (abmr, tcmr, bdl, mixed, o...
ABMR                                                            0     0
Borderline                                                      0     0
Mixed                                                           0     0
NA                                                              6     4
Others                                                          0     0
TCMR                                                            0    28

diagnosis (tcmr,non-tcmr, nephrectomies)            non-TCMR
histologic diagnosis (abmr, tcmr, bdl, mixed, o...
ABMR                                                      32
Borderline                                                42
Mixed                                                      4
NA                                                        38
Others                                                   151
TCMR                                                       1

In [21]:
LABEL_MAP_48581 = {
    "others": "NR",
    "abmr": "ABMR",
    "tcmr": "TCMR",
    "mixed": "Mixed",
    # "borderline" intentionally excluded from main task
}

meta_48581["rejection_class"] = (
    meta_48581[HIST_COL].str.lower().str.strip().map(LABEL_MAP_48581)
)

print("Main 4-class distribution:")
print(meta_48581["rejection_class"].value_counts(dropna=False))

# Set aside Borderline samples separately — useful later for uncertainty/ambiguous-case analysis
meta_48581_borderline = meta_48581[meta_48581[HIST_COL].str.lower().str.strip() == "borderline"].copy()
print(f"\nSet aside {len(meta_48581_borderline)} Borderline samples for later ambiguous-case analysis")

meta_48581_clean = meta_48581.dropna(subset=["rejection_class"]).copy()
print(f"\nFinal GSE48581 labeled samples: {len(meta_48581_clean)}")
print(meta_48581_clean["rejection_class"].value_counts())

Main 4-class distribution:
rejection_class
NR       151
NaN       90
ABMR      32
TCMR      29
Mixed      4
Name: count, dtype: int64

Set aside 42 Borderline samples for later ambiguous-case analysis

Final GSE48581 labeled samples: 216
rejection_class
NR       151
ABMR      32
TCMR      29
Mixed      4
Name: count, dtype: int64

In [22]:
LABEL_MAP_48581 = {
    "others": "NR",
    "abmr": "ABMR",
    "tcmr": "TCMR",
    "mixed": "Mixed",
}

meta_48581["rejection_class"] = (
    meta_48581[HIST_COL].str.lower().str.strip().map(LABEL_MAP_48581)
)

print("Main 4-class distribution:")
print(meta_48581["rejection_class"].value_counts(dropna=False))

meta_48581_borderline = meta_48581[meta_48581[HIST_COL].str.lower().str.strip() == "borderline"].copy()
print(f"\nSet aside {len(meta_48581_borderline)} Borderline samples for later ambiguous-case analysis")

meta_48581_clean = meta_48581.dropna(subset=["rejection_class"]).copy()
print(f"\nFinal GSE48581 labeled samples: {len(meta_48581_clean)}")
print(meta_48581_clean["rejection_class"].value_counts())

Main 4-class distribution:
rejection_class
NR       151
NaN       90
ABMR      32
TCMR      29
Mixed      4
Name: count, dtype: int64

Set aside 42 Borderline samples for later ambiguous-case analysis

Final GSE48581 labeled samples: 216
rejection_class
NR       151
ABMR      32
TCMR      29
Mixed      4
Name: count, dtype: int64

In [23]:
expr_frames = []
for gsm_name in meta_48581_clean.index:
    gsm = gse_48581.gsms[gsm_name]
    if gsm.table is None or gsm.table.empty:
        continue
    series = gsm.table.set_index("ID_REF")["VALUE"]
    series.name = gsm_name
    expr_frames.append(series)

expr_48581 = pd.concat(expr_frames, axis=1)
print("Raw expression matrix shape (probes x samples):", expr_48581.shape)

# Same platform as GSE36059 (GPL570), so reuse the same probe_to_gene mapping
expr_48581_genes = expr_48581.join(probe_to_gene.rename("gene_symbol"), how="left")

before = len(expr_48581_genes)
expr_48581_genes = expr_48581_genes.dropna(subset=["gene_symbol"])
expr_48581_genes = expr_48581_genes[expr_48581_genes["gene_symbol"].str.strip() != ""]
print(f"Dropped {before - len(expr_48581_genes)} unannotated/control probes")

expr_48581_final = expr_48581_genes.groupby("gene_symbol").mean(numeric_only=True)
print("Gene-level expression matrix shape (genes x samples):", expr_48581_final.shape)

Raw expression matrix shape (probes x samples): (54675, 216)
Dropped 8893 unannotated/control probes
Gene-level expression matrix shape (genes x samples): (23520, 216)

In [24]:
common_samples = expr_48581_final.columns.intersection(meta_48581_clean.index)
print(f"Samples in expression matrix: {expr_48581_final.shape[1]}")
print(f"Samples in metadata: {len(meta_48581_clean)}")
print(f"Common samples: {len(common_samples)}")

expr_48581_final = expr_48581_final[common_samples]
meta_48581_clean = meta_48581_clean.loc[common_samples]

assert (expr_48581_final.columns == meta_48581_clean.index).all()
print("Aligned successfully:", expr_48581_final.shape[1], "samples")

Samples in expression matrix: 216
Samples in metadata: 216
Common samples: 216
Aligned successfully: 216 samples

In [25]:
expr_48581_final.to_parquet(os.path.join(PROCESSED_DIR, "GSE48581_expression.parquet"))
meta_48581_clean.to_parquet(os.path.join(PROCESSED_DIR, "GSE48581_metadata.parquet"))
meta_48581_borderline.to_parquet(os.path.join(PROCESSED_DIR, "GSE48581_borderline_setaside.parquet"))

print("Saved:")
print(" -", "GSE48581_expression.parquet", expr_48581_final.shape)
print(" -", "GSE48581_metadata.parquet", meta_48581_clean.shape)
print(" -", "GSE48581_borderline_setaside.parquet", meta_48581_borderline.shape)

Saved:
 - GSE48581_expression.parquet (23520, 216)
 - GSE48581_metadata.parquet (216, 5)
 - GSE48581_borderline_setaside.parquet (42, 5)

In [26]:
gse_98320 = GEOparse.get_GEO(geo="GSE98320", destdir=RAW_DIR)
print("Samples in GSE98320:", len(gse_98320.gsms))
print("Platforms:", list(gse_98320.gpls.keys()))

05-Sep-2026 02:12:46 DEBUG utils - Directory /path/to/kidney-rejection-project/dataset/raw already exists. Skipping.
05-Sep-2026 02:12:46 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE98nnn/GSE98320/soft/GSE98320_family.soft.gz to /path/to/kidney-rejection-project/dataset/raw/GSE98320_family.soft.gz
100%|██████████| 537M/537M [00:14<00:00, 38.1MB/s]
05-Sep-2026 02:13:01 DEBUG downloader - Size validation passed
05-Sep-2026 02:13:01 DEBUG downloader - Moving /tmp/tmpd9u_czrh to /path/to/kidney-rejection-project/dataset/raw/GSE98320_family.soft.gz
05-Sep-2026 02:13:01 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE98nnn/GSE98320/soft/GSE98320_family.soft.gz
05-Sep-2026 02:13:01 INFO GEOparse - Parsing /path/to/kidney-rejection-project/dataset/raw/GSE98320_family.soft.gz:
05-Sep-2026 02:13:01 DEBUG GEOparse - DATABASE: GeoMiame
05-Sep-2026 02:13:01 DEBUG GEOparse - SERIES: GSE98320
05-Sep-2026 02:13:01 DEBUG GEOparse - PLATFORM: GPL15207
/usr/local/lib/python3.12/dist-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590943
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590944
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590945
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590946
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590947
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590948
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590949
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590950
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590951
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590952
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590953
05-Sep-2026 02:13:08 DEBUG GEOparse - SAMPLE: GSM2590954
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590955
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590956
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590957
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590958
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590959
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590960
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590961
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590962
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590963
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590964
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590965
05-Sep-2026 02:13:09 DEBUG GEOparse - SAMPLE: GSM2590966
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590967
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590968
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590969
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590970
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590971
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590972
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590973
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590974
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590975
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590976
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590977
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590978
05-Sep-2026 02:13:10 DEBUG GEOparse - SAMPLE: GSM2590979
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590980
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590981
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590982
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590983
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590984
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590985
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590986
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590987
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590988
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590989
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590990
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590991
05-Sep-2026 02:13:11 DEBUG GEOparse - SAMPLE: GSM2590992
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2590993
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2590994
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2590995
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2590996
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2590997
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2590998
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2590999
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2591000
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2591001
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2591002
05-Sep-2026 02:13:12 DEBUG GEOparse - SAMPLE: GSM2591003
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591004
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591005
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591006
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591007
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591008
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591009
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591010
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591011
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591012
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591013
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591014
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591015
05-Sep-2026 02:13:13 DEBUG GEOparse - SAMPLE: GSM2591016
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591017
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591018
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591019
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591020
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591021
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591022
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591023
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591024
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591025
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591026
05-Sep-2026 02:13:14 DEBUG GEOparse - SAMPLE: GSM2591027
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591028
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591029
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591030
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591031
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591032
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591033
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591034
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591035
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591036
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591037
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591038
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591039
05-Sep-2026 02:13:15 DEBUG GEOparse - SAMPLE: GSM2591040
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591041
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591042
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591043
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591044
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591045
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591046
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591047
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591048
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591049
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591050
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591051
05-Sep-2026 02:13:16 DEBUG GEOparse - SAMPLE: GSM2591052
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591053
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591054
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591055
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591056
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591057
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591058
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591059
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591060
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591061
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591062
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591063
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591064
05-Sep-2026 02:13:17 DEBUG GEOparse - SAMPLE: GSM2591065
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591066
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591067
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591068
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591069
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591070
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591071
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591072
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591073
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591074
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591075
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591076
05-Sep-2026 02:13:18 DEBUG GEOparse - SAMPLE: GSM2591077
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591078
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591079
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591080
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591081
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591082
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591083
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591084
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591085
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591086
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591087
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591088
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591089
05-Sep-2026 02:13:19 DEBUG GEOparse - SAMPLE: GSM2591090
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591091
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591092
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591093
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591094
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591095
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591096
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591097
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591098
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591099
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591100
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591101
05-Sep-2026 02:13:20 DEBUG GEOparse - SAMPLE: GSM2591102
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591103
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591104
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591105
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591106
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591107
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591108
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591109
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591110
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591111
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591112
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591113
05-Sep-2026 02:13:21 DEBUG GEOparse - SAMPLE: GSM2591114
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591115
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591116
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591117
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591118
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591119
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591120
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591121
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591122
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591123
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591124
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591125
05-Sep-2026 02:13:22 DEBUG GEOparse - SAMPLE: GSM2591126
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591127
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591128
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591129
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591130
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591131
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591132
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591133
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591134
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591135
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591136
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591137
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591138
05-Sep-2026 02:13:23 DEBUG GEOparse - SAMPLE: GSM2591139
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591140
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591141
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591142
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591143
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591144
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591145
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591146
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591147
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591148
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591149
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591150
05-Sep-2026 02:13:24 DEBUG GEOparse - SAMPLE: GSM2591151
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591152
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591153
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591154
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591155
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591156
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591157
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591158
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591159
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591160
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591161
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591162
05-Sep-2026 02:13:25 DEBUG GEOparse - SAMPLE: GSM2591163
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591164
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591165
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591166
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591167
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591168
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591169
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591170
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591171
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591172
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591173
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591174
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591175
05-Sep-2026 02:13:26 DEBUG GEOparse - SAMPLE: GSM2591176
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591177
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591178
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591179
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591180
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591181
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591182
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591183
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591184
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591185
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591186
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591187
05-Sep-2026 02:13:27 DEBUG GEOparse - SAMPLE: GSM2591188
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591189
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591190
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591191
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591192
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591193
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591194
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591195
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591196
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591197
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591198
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591199
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591200
05-Sep-2026 02:13:28 DEBUG GEOparse - SAMPLE: GSM2591201
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591202
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591203
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591204
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591205
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591206
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591207
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591208
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591209
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591210
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591211
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591212
05-Sep-2026 02:13:29 DEBUG GEOparse - SAMPLE: GSM2591213
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591214
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591215
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591216
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591217
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591218
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591219
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591220
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591221
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591222
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591223
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591224
05-Sep-2026 02:13:30 DEBUG GEOparse - SAMPLE: GSM2591225
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591226
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591227
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591228
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591229
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591230
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591231
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591232
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591233
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591234
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591235
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591236
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591237
05-Sep-2026 02:13:31 DEBUG GEOparse - SAMPLE: GSM2591238
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591239
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591240
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591241
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591242
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591243
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591244
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591245
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591246
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591247
05-Sep-2026 02:13:32 DEBUG GEOparse - SAMPLE: GSM2591248
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591249
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591250
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591251
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591252
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591253
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591254
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591255
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591256
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591257
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591258
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591259
05-Sep-2026 02:13:33 DEBUG GEOparse - SAMPLE: GSM2591260
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591261
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591262
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591263
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591264
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591265
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591266
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591267
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591268
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591269
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591270
05-Sep-2026 02:13:34 DEBUG GEOparse - SAMPLE: GSM2591271

Samples in GSE98320: 1208
Platforms: ['GPL15207']

In [27]:
for i, (gsm_name, gsm) in enumerate(gse_98320.gsms.items()):
    if i >= 8:
        break
    print(gsm_name, "->", gsm.metadata.get("characteristics_ch1", []))

GSM2590943 -> ['tissue: kidney', 'archetype cluster: 2', 'd96: TCMR', 'g: 0', 'cg: 0', 'i: 2', 'ci: 3', 't: 3', 'ct: 3', 'v: 0', 'cv: 1', 'ah: NA', 'ptc: 0', 'c4d: 0', 'in i-ifta set n=234?: 0', 'mmdx: -', 'ifta (0, <10%, ≥10%): -']
GSM2590944 -> ['tissue: kidney', 'archetype cluster: 4', 'd96: TCMR', 'g: 0', 'cg: 1', 'i: 3', 'ci: 2', 't: 3', 'ct: 2', 'v: 0', 'cv: 1', 'ah: 1', 'ptc: 1', 'c4d: 1', 'in i-ifta set n=234?: 0', 'mmdx: -', 'ifta (0, <10%, ≥10%): -']
GSM2590945 -> ['tissue: kidney', 'archetype cluster: 1', 'd96: Bord.', 'g: NA', 'cg: NA', 'i: NA', 'ci: NA', 't: NA', 'ct: NA', 'v: NA', 'cv: NA', 'ah: NA', 'ptc: NA', 'c4d: 0', 'in i-ifta set n=234?: 1', 'mmdx: NR', 'ifta (0, <10%, ≥10%): <10%']
GSM2590946 -> ['tissue: kidney', 'archetype cluster: 5', 'd96: ABMR', 'g: 1', 'cg: 1', 'i: 0', 'ci: 2', 't: 0', 'ct: 2', 'v: 0', 'cv: 2', 'ah: 3', 'ptc: 1', 'c4d: 0', 'in i-ifta set n=234?: 0', 'mmdx: -', 'ifta (0, <10%, ≥10%): -']
GSM2590947 -> ['tissue: kidney', 'archetype cluster: 1', 'd96: AKI', 'g: NA', 'cg: NA', 'i: NA', 'ci: NA', 't: NA', 'ct: NA', 'v: NA', 'cv: NA', 'ah: NA', 'ptc: NA', 'c4d: 0', 'in i-ifta set n=234?: 1', 'mmdx: NR', 'ifta (0, <10%, ≥10%): 0']
GSM2590948 -> ['tissue: kidney', 'archetype cluster: 4', 'd96: ABMR', 'g: 1', 'cg: 0', 'i: 0', 'ci: 0', 't: 0', 'ct: 0', 'v: NA', 'cv: NA', 'ah: 0', 'ptc: 1', 'c4d: 2', 'in i-ifta set n=234?: 0', 'mmdx: -', 'ifta (0, <10%, ≥10%): -']
GSM2590949 -> ['tissue: kidney', 'archetype cluster: 1', 'd96: GN', 'g: NA', 'cg: NA', 'i: NA', 'ci: NA', 't: NA', 'ct: NA', 'v: NA', 'cv: NA', 'ah: NA', 'ptc: NA', 'c4d: 0', 'in i-ifta set n=234?: 1', 'mmdx: ABMR', 'ifta (0, <10%, ≥10%): ≥10%']
GSM2590950 -> ['tissue: kidney', 'archetype cluster: 1', 'd96: IFTA', 'g: 0', 'cg: 0', 'i: 0', 'ci: 3', 't: 0', 'ct: 3', 'v: 0', 'cv: 1', 'ah: 3', 'ptc: 0', 'c4d: 0', 'in i-ifta set n=234?: 0', 'mmdx: -', 'ifta (0, <10%, ≥10%): -']

In [28]:
platform_ids = list(gse_98320.gpls.keys())
print("Platform(s):", platform_ids)

gpl_98320 = gse_98320.gpls[platform_ids[0]]
anno_98320 = gpl_98320.table
print("Annotation columns:", anno_98320.columns.tolist())
anno_98320.head()

Platform(s): ['GPL15207']
Annotation columns: ['ID', 'GeneChip Array', 'Species Scientific Name', 'Annotation Date', 'Sequence Type', 'Sequence Source', 'Transcript ID(Array Design)', 'Target Description', 'GB_ACC', 'GI', 'Representative Public ID', 'Archival UniGene Cluster', 'UniGene ID', 'Genome Version', 'Alignments', 'Gene Title', 'Gene Symbol', 'Chromosomal Location', 'Unigene Cluster Type', 'Ensembl', 'Entrez Gene', 'SwissProt', 'EC', 'OMIM', 'RefSeq Protein ID', 'RefSeq Transcript ID', 'Gene Ontology Biological Process', 'Gene Ontology Cellular Component', 'Gene Ontology Molecular Function', 'Pathway', 'InterPro', 'Annotation Description', 'Annotation Transcript Cluster', 'Transcript Assignments', 'Annotation Notes', 'SPOT_ID']

,ID,GeneChip Array,Species Scientific Name,Annotation Date,Sequence Type,Sequence Source,Transcript ID(Array Design),Target Description,GB_ACC,GI,...,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function,Pathway,InterPro,Annotation Description,Annotation Transcript Cluster,Transcript Assignments,Annotation Notes,SPOT_ID
0,11715100_at,Human Genome PrimeView Array,Homo sapiens,30-Mar-16,Consensus sequence,Affymetrix Proprietary Database,g21264570,g21264570 /TID=g21264570 /CNT=1 /FEA=FLmRNA /T...,NaN,21264570.0,...,0000183 // chromatin silencing at rDNA // trac...,0000228 // nuclear chromosome // inferred from...,0003677 // DNA binding // inferred from electr...,---,IPR007125 // Histone H2A/H2B/H3 // 9.3E-34 ///...,This probe set was annotated using the Matchin...,"ENST00000614378(11),NM_003534(11),OTTHUMT00000...",ENST00000614378 // ensembl_havana_transcript:k...,---,NaN
1,11715101_s_at,Human Genome PrimeView Array,Homo sapiens,30-Mar-16,Consensus sequence,Affymetrix Proprietary Database,g21264570,g21264570 /TID=g21264570 /CNT=1 /FEA=FLmRNA /T...,NaN,21264570.0,...,0000183 // chromatin silencing at rDNA // trac...,0000228 // nuclear chromosome // inferred from...,0003677 // DNA binding // inferred from electr...,---,IPR007125 // Histone H2A/H2B/H3 // 9.3E-34 ///...,This probe set was annotated using the Matchin...,"ENST00000614378(11),NM_003534(11),OTTHUMT00000...",ENST00000614378 // ensembl_havana_transcript:k...,---,NaN
2,11715102_x_at,Human Genome PrimeView Array,Homo sapiens,30-Mar-16,Consensus sequence,Affymetrix Proprietary Database,g21264570,g21264570 /TID=g21264570 /CNT=1 /FEA=FLmRNA /T...,NaN,21264570.0,...,0000183 // chromatin silencing at rDNA // trac...,0000228 // nuclear chromosome // inferred from...,0003677 // DNA binding // inferred from electr...,---,IPR007125 // Histone H2A/H2B/H3 // 9.3E-34 ///...,This probe set was annotated using the Matchin...,"ENST00000614378(11),NM_003534(11),OTTHUMT00000...",ENST00000614378 // ensembl_havana_transcript:k...,GENSCAN00000029819 // ensembl // 4 // Cross Hy...,NaN
3,11715103_x_at,Human Genome PrimeView Array,Homo sapiens,30-Mar-16,Consensus sequence,Affymetrix Proprietary Database,g22748780,g22748780 /TID=g22748780 /CNT=1 /FEA=FLmRNA /T...,NaN,22748780.0,...,0032007 // negative regulation of TOR signalin...,0005737 // cytoplasm // not recorded /// 00057...,0005515 // protein binding // inferred from ph...,---,IPR008477 // Protein of unknown function DUF75...,This probe set was annotated using the Matchin...,"BC017672(11),BC044250(9),ENST00000327473(11),E...",BC017672 // Homo sapiens tumor necrosis factor...,---,NaN
4,11715104_s_at,Human Genome PrimeView Array,Homo sapiens,30-Mar-16,Consensus sequence,Affymetrix Proprietary Database,g30039713,g30039713 /TID=g30039713 /CNT=1 /FEA=FLmRNA /T...,NaN,30039713.0,...,---,0016020 // membrane // inferred from electroni...,---,---,IPR004878 // Otopetrin // 9.4E-43 /// IPR00487...,This probe set was annotated using the Matchin...,"ENST00000331427(11),ENST00000580223(11),NM_178...",ENST00000331427 // ensembl:known chromosome:GR...,---,NaN

In [29]:
rows = []
for gsm_name, gsm in gse_98320.gsms.items():
    chars = extract_characteristics(gsm)
    chars["sample_id"] = gsm_name
    rows.append(chars)

meta_98320 = pd.DataFrame(rows).set_index("sample_id")
print(meta_98320.columns.tolist())

print("\nd96 (histologic diagnosis) counts:")
print(meta_98320["d96"].value_counts(dropna=False))

print("\nmmdx (molecular diagnosis) counts:")
print(meta_98320["mmdx"].value_counts(dropna=False))

print("\nCross-tab: d96 vs mmdx:")
print(pd.crosstab(meta_98320["d96"], meta_98320["mmdx"]))

['tissue', 'archetype cluster', 'd96', 'g', 'cg', 'i', 'ci', 't', 'ct', 'v', 'cv', 'ah', 'ptc', 'c4d', 'in i-ifta set n=234?', 'mmdx', 'ifta (0, <10%, ≥10%)']

d96 (histologic diagnosis) counts:
d96
NOMOA       274
ABMR        215
IFTA        145
Bord.       109
GN           97
AKI          96
TCMR         87
Mixed        41
TG           40
BK           37
Other        25
ABMRsusp     24
DiabNeph     18
Name: count, dtype: int64

mmdx (molecular diagnosis) counts:
mmdx
-        974
NR       132
ABMR      66
TCMR      24
Mixed     12
Name: count, dtype: int64

Cross-tab: d96 vs mmdx:
mmdx        -  ABMR  Mixed  NR  TCMR
d96
ABMR      173    31      2   8     1
ABMRsusp   24     0      0   0     0
AKI        65     2      0  29     0
BK         33     0      0   2     2
Bord.      76     5      2  20     6
DiabNeph   18     0      0   0     0
GN         76     5      0  14     2
IFTA      131     2      0  11     1
Mixed      26    12      3   0     0
NOMOA     237     2      0  34     1
Other      12     4      1   7     1
TCMR       67     1      4   5    10
TG         36     2      0   2     0

In [30]:
meta_98320["rejection_class"] = meta_98320["mmdx"].replace("-", pd.NA)

print("Final GSE98320 (mmdx-labeled) distribution:")
print(meta_98320["rejection_class"].value_counts(dropna=False))

meta_98320_clean = meta_98320.dropna(subset=["rejection_class"]).copy()
print(f"\nFinal GSE98320 labeled samples: {len(meta_98320_clean)}")

Final GSE98320 (mmdx-labeled) distribution:
rejection_class
<NA>     974
NR       132
ABMR      66
TCMR      24
Mixed     12
Name: count, dtype: int64

Final GSE98320 labeled samples: 234

In [31]:
probe_to_gene_98320 = anno_98320.set_index("ID")["Gene Symbol"]

expr_frames = []
for gsm_name in meta_98320_clean.index:
    gsm = gse_98320.gsms[gsm_name]
    if gsm.table is None or gsm.table.empty:
        continue
    series = gsm.table.set_index("ID_REF")["VALUE"]
    series.name = gsm_name
    expr_frames.append(series)

expr_98320 = pd.concat(expr_frames, axis=1)
print("Raw expression matrix shape:", expr_98320.shape)

expr_98320_genes = expr_98320.join(probe_to_gene_98320.rename("gene_symbol"), how="left")
before = len(expr_98320_genes)
expr_98320_genes = expr_98320_genes.dropna(subset=["gene_symbol"])
expr_98320_genes = expr_98320_genes[expr_98320_genes["gene_symbol"].str.strip() != ""]
print(f"Dropped {before - len(expr_98320_genes)} unannotated/control probes")

expr_98320_final = expr_98320_genes.groupby("gene_symbol").mean(numeric_only=True)
print("Gene-level expression matrix shape:", expr_98320_final.shape)

Raw expression matrix shape: (49395, 234)
Dropped 23 unannotated/control probes
Gene-level expression matrix shape: (20085, 234)

In [32]:
common_samples = expr_98320_final.columns.intersection(meta_98320_clean.index)
expr_98320_final = expr_98320_final[common_samples]
meta_98320_clean = meta_98320_clean.loc[common_samples]
assert (expr_98320_final.columns == meta_98320_clean.index).all()
print("Aligned:", expr_98320_final.shape[1], "samples")

expr_98320_final.to_parquet(os.path.join(PROCESSED_DIR, "GSE98320_expression.parquet"))
meta_98320_clean.to_parquet(os.path.join(PROCESSED_DIR, "GSE98320_metadata.parquet"))
print("Saved GSE98320 processed data:", expr_98320_final.shape)

Aligned: 234 samples
Saved GSE98320 processed data: (20085, 234)

In [33]:
expr_36059 = pd.read_parquet(os.path.join(PROCESSED_DIR, "GSE36059_expression.parquet"))
meta_36059 = pd.read_parquet(os.path.join(PROCESSED_DIR, "GSE36059_metadata.parquet"))

expr_48581 = pd.read_parquet(os.path.join(PROCESSED_DIR, "GSE48581_expression.parquet"))
meta_48581 = pd.read_parquet(os.path.join(PROCESSED_DIR, "GSE48581_metadata.parquet"))

expr_98320 = pd.read_parquet(os.path.join(PROCESSED_DIR, "GSE98320_expression.parquet"))
meta_98320 = pd.read_parquet(os.path.join(PROCESSED_DIR, "GSE98320_metadata.parquet"))

meta_36059["study"] = "GSE36059"
meta_48581["study"] = "GSE48581"
meta_98320["study"] = "GSE98320"

print("GSE36059:", expr_36059.shape, meta_36059.shape)
print("GSE48581:", expr_48581.shape, meta_48581.shape)
print("GSE98320:", expr_98320.shape, meta_98320.shape)

GSE36059: (23520, 403) (403, 5)
GSE48581: (23520, 216) (216, 6)
GSE98320: (20085, 234) (234, 19)

In [34]:
common_genes = sorted(set(expr_36059.index) & set(expr_48581.index) & set(expr_98320.index))
print(f"Common genes across all 3 datasets: {len(common_genes)}")

expr_36059_c = expr_36059.loc[common_genes]
expr_48581_c = expr_48581.loc[common_genes]
expr_98320_c = expr_98320.loc[common_genes]

combined_expr = pd.concat([expr_36059_c, expr_48581_c, expr_98320_c], axis=1)

combined_meta = pd.concat([
    meta_36059[["rejection_class", "study"]],
    meta_48581[["rejection_class", "study"]],
    meta_98320[["rejection_class", "study"]],
])

print("Combined expression matrix:", combined_expr.shape)
print("Combined metadata:", combined_meta.shape)
print(combined_meta.groupby(["study", "rejection_class"]).size())

Common genes across all 3 datasets: 17343
Combined expression matrix: (17343, 853)
Combined metadata: (853, 2)
study     rejection_class
GSE36059  ABMR                65
          Mixed               22
          NR                 281
          TCMR                35
GSE48581  ABMR                32
          Mixed                4
          NR                 151
          TCMR                29
GSE98320  ABMR                66
          Mixed               12
          NR                 132
          TCMR                24
dtype: int64

In [35]:
dupe_ids = combined_meta.index[combined_meta.index.duplicated(keep=False)]
print(f"Duplicate sample IDs across datasets: {len(dupe_ids)}")
if len(dupe_ids) > 0:
    print(dupe_ids.tolist())

Duplicate sample IDs across datasets: 0

In [36]:
print("GSE36059 value range:", expr_36059_c.values.min(), "-", expr_36059_c.values.max())
print("GSE48581 value range:", expr_48581_c.values.min(), "-", expr_48581_c.values.max())
print("GSE98320 value range:", expr_98320_c.values.min(), "-", expr_98320_c.values.max())

GSE36059 value range: 2.559165237 - 14.622887723333333
GSE48581 value range: 2.807352202 - 15.45616094
GSE98320 value range: 1.800756976 - 14.81021783

In [37]:
from combat.pycombat import pycombat

# pycombat expects: expression dataframe (genes x samples), batch labels aligned to columns
batch_labels = combined_meta.loc[combined_expr.columns, "study"]

combined_expr_corrected = pycombat(combined_expr, batch_labels)

print("Batch-corrected expression matrix shape:", combined_expr_corrected.shape)
print("Value range after correction:", combined_expr_corrected.values.min(), "-", combined_expr_corrected.values.max())

Found 3 batches.
Adjusting for 0 covariate(s) or covariate level(s).
Standardizing Data across genes.
Fitting L/S model and finding priors.
Finding parametric adjustments.
Adjusting the Data
Batch-corrected expression matrix shape: (17343, 853)
Value range after correction: 2.3311759364686377 - 15.334906859478371

In [39]:
from sklearn.model_selection import train_test_split

RANDOM_SEED = 42
TRAIN_FRAC, VAL_FRAC, TEST_FRAC = 0.70, 0.15, 0.15

train_ids, temp_ids = train_test_split(
    combined_meta.index,
    test_size=(1 - TRAIN_FRAC),
    stratify=combined_meta["rejection_class"],
    random_state=RANDOM_SEED,
)

val_size = VAL_FRAC / (VAL_FRAC + TEST_FRAC)
val_ids, test_ids = train_test_split(
    combined_meta.loc[temp_ids].index,
    test_size=(1 - val_size),
    stratify=combined_meta.loc[temp_ids, "rejection_class"],
    random_state=RANDOM_SEED,
)

combined_meta["split"] = "train"
combined_meta.loc[val_ids, "split"] = "val"
combined_meta.loc[test_ids, "split"] = "test"

print(combined_meta.groupby(["split", "rejection_class"]).size().unstack(fill_value=0))

ImportError: cannot import name '_center' from 'numpy._core.umath' (/usr/local/lib/python3.12/dist-packages/numpy/_core/umath.py)

In [40]:
import numpy as np

RANDOM_SEED = 42
TRAIN_FRAC, VAL_FRAC, TEST_FRAC = 0.70, 0.15, 0.15

rng = np.random.default_rng(RANDOM_SEED)

combined_meta["split"] = None

for cls, group in combined_meta.groupby("rejection_class"):
    ids = group.index.to_numpy().copy()
    rng.shuffle(ids)

    n = len(ids)
    n_train = int(round(n * TRAIN_FRAC))
    n_val = int(round(n * VAL_FRAC))

    train_ids = ids[:n_train]
    val_ids = ids[n_train:n_train + n_val]
    test_ids = ids[n_train + n_val:]

    combined_meta.loc[train_ids, "split"] = "train"
    combined_meta.loc[val_ids, "split"] = "val"
    combined_meta.loc[test_ids, "split"] = "test"

print(combined_meta.groupby(["split", "rejection_class"]).size().unstack(fill_value=0))

rejection_class  ABMR  Mixed   NR  TCMR
split
test               25      5   84    13
train             114     27  395    62
val                24      6   85    13

In [41]:
final_dataset = combined_expr_corrected.T  # rows = samples, columns = genes
final_dataset = final_dataset.join(combined_meta[["study", "rejection_class", "split"]])

print("Final dataset shape (samples x [genes + metadata]):", final_dataset.shape)
final_dataset.head()

Final dataset shape (samples x [genes + metadata]): (853, 17346)

,A1BG,A1CF,A2M,A2ML1,A4GALT,A4GNT,AAAS,AACS,AACSP1,AADAC,...,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3,study,rejection_class,split
GSM880204,4.949554,8.812880,9.310871,4.088609,6.692914,5.016908,7.743009,7.424312,3.904078,4.483908,...,5.057694,6.588527,5.833452,8.037167,8.044328,6.784398,7.514997,GSE36059,NR,train
GSM880205,5.449884,7.011610,9.376565,3.922192,6.620855,4.952195,7.561618,7.524828,3.707032,4.309660,...,5.117232,6.676183,4.889207,7.919181,8.426617,6.763044,7.695279,GSE36059,NR,train
GSM880206,5.283740,8.619844,9.283428,4.166646,6.695407,4.958830,7.125557,7.416844,4.090111,4.198785,...,5.032441,6.558074,5.576357,8.080631,7.603573,6.742642,7.930000,GSE36059,NR,train
GSM880207,5.125154,7.800087,9.278675,4.054371,6.449539,4.941438,7.094852,7.868014,4.153760,4.367994,...,5.154505,6.646622,5.943569,8.333903,7.806346,6.747263,7.276592,GSE36059,NR,test
GSM880208,5.073927,5.843541,9.377556,4.062290,6.455212,4.913541,7.703463,8.005449,3.683217,4.310145,...,5.083311,6.699159,5.056642,8.028001,8.231566,6.824338,7.858534,GSE36059,NR,train

In [43]:
parquet_path = os.path.join(PROCESSED_DIR, "combined_dataset.parquet")
final_dataset.to_parquet(parquet_path)
print("Saved Parquet:", parquet_path)

print("\nFinal file sizes:")
for f in ["combined_dataset.csv", "combined_dataset.parquet"]:
    p = os.path.join(PROCESSED_DIR, f)
    size_mb = os.path.getsize(p) / (1024 * 1024)
    print(f"  {f}: {size_mb:.1f} MB")

Saved Parquet: /path/to/kidney-rejection-project/dataset/processed/combined_dataset.parquet

Final file sizes:
  combined_dataset.csv: 254.7 MB
  combined_dataset.parquet: 139.7 MB

In [44]:
CLINICAL_COLS = ["g", "cg", "i", "ci", "t", "ct", "v", "cv", "ah", "ptc", "c4d"]

clinical_98320 = meta_98320[CLINICAL_COLS].copy()

# these are stored as strings (e.g. "0", "1", "NA") — convert to numeric, NA -> NaN
for col in CLINICAL_COLS:
    clinical_98320[col] = pd.to_numeric(clinical_98320[col], errors="coerce")

print("Clinical feature table shape:", clinical_98320.shape)
print("\nMissingness per column:")
print(clinical_98320.isna().sum())
clinical_98320.describe()

Clinical feature table shape: (234, 11)

Missingness per column:
g      234
cg     234
i      234
ci     234
t      234
ct     234
v      234
cv     234
ah     234
ptc    234
c4d      0
dtype: int64

         g   cg    i   ci    t   ct    v   cv   ah  ptc    c4d
count  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  234.0
mean   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.0
std    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.0
min    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.0
25%    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.0
50%    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.0
75%    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.0
max    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.0

In [52]:
# Rebuild from the original gse_98320 GEOparse object (should still be in memory from Cell 24)
rows = []
for gsm_name, gsm in gse_98320.gsms.items():
    chars = extract_characteristics(gsm)
    chars["sample_id"] = gsm_name
    rows.append(chars)

meta_98320_full = pd.DataFrame(rows).set_index("sample_id")
print("Full GSE98320 metadata shape:", meta_98320_full.shape)
print(meta_98320_full["mmdx"].value_counts())

Full GSE98320 metadata shape: (1208, 17)
mmdx
-        974
NR       132
ABMR      66
TCMR      24
Mixed     12
Name: count, dtype: int64

In [53]:
non_mmdx = meta_98320_full[meta_98320_full["mmdx"] == "-"].copy()
print("Samples with d96 histologic label but no mmdx label:", len(non_mmdx))

clinical_non_mmdx = non_mmdx[CLINICAL_COLS].copy()
for col in CLINICAL_COLS:
    clinical_non_mmdx[col] = pd.to_numeric(clinical_non_mmdx[col], errors="coerce")

print("\nMissingness per column (out of", len(non_mmdx), "):")
print(clinical_non_mmdx.isna().sum())

Samples with d96 histologic label but no mmdx label: 974

Missingness per column (out of 974 ):
g       30
cg      35
i       20
ci      36
t       21
ct      35
v       71
cv     112
ah      57
ptc     38
c4d     70
dtype: int64

In [54]:
LABEL_MAP_D96 = {
    "nomoa": "NR",
    "aki": "NR",
    "ifta": "NR",
    "bk": "NR",
    "abmr": "ABMR",
    "tcmr": "TCMR",
    "mixed": "Mixed",
    # bord., abmrsusp, tg, gn, diabneph, other -> intentionally excluded
}

non_mmdx["rejection_class"] = (
    non_mmdx["d96"].str.lower().str.strip().map(LABEL_MAP_D96)
)

print("Mapped distribution (before dropping unmapped):")
print(non_mmdx["rejection_class"].value_counts(dropna=False))

meta_98320_clinical = non_mmdx.dropna(subset=["rejection_class"]).copy()
print(f"\nFinal usable clinical-branch samples: {len(meta_98320_clinical)}")
print(meta_98320_clinical["rejection_class"].value_counts())

Mapped distribution (before dropping unmapped):
rejection_class
NR       466
NaN      242
ABMR     173
TCMR      67
Mixed     26
Name: count, dtype: int64

Final usable clinical-branch samples: 732
rejection_class
NR       466
ABMR     173
TCMR      67
Mixed     26
Name: count, dtype: int64

In [55]:
expr_frames = []
for gsm_name in meta_98320_clinical.index:
    gsm = gse_98320.gsms[gsm_name]
    if gsm.table is None or gsm.table.empty:
        continue
    series = gsm.table.set_index("ID_REF")["VALUE"]
    series.name = gsm_name
    expr_frames.append(series)

expr_98320_clinical = pd.concat(expr_frames, axis=1)
print("Raw expression matrix shape:", expr_98320_clinical.shape)

# Reuse probe_to_gene_98320 mapping from Cell 29 (same platform, GPL15207)
expr_98320_clinical_genes = expr_98320_clinical.join(probe_to_gene_98320.rename("gene_symbol"), how="left")
before = len(expr_98320_clinical_genes)
expr_98320_clinical_genes = expr_98320_clinical_genes.dropna(subset=["gene_symbol"])
expr_98320_clinical_genes = expr_98320_clinical_genes[expr_98320_clinical_genes["gene_symbol"].str.strip() != ""]
print(f"Dropped {before - len(expr_98320_clinical_genes)} unannotated/control probes")

expr_98320_clinical_final = expr_98320_clinical_genes.groupby("gene_symbol").mean(numeric_only=True)
print("Gene-level expression matrix shape:", expr_98320_clinical_final.shape)

Raw expression matrix shape: (49395, 732)
Dropped 23 unannotated/control probes
Gene-level expression matrix shape: (20085, 732)

In [56]:
common_samples = expr_98320_clinical_final.columns.intersection(meta_98320_clinical.index)
print(f"Samples in expression matrix: {expr_98320_clinical_final.shape[1]}")
print(f"Samples in metadata: {len(meta_98320_clinical)}")
print(f"Common samples: {len(common_samples)}")

expr_98320_clinical_final = expr_98320_clinical_final[common_samples]
meta_98320_clinical = meta_98320_clinical.loc[common_samples]

assert (expr_98320_clinical_final.columns == meta_98320_clinical.index).all()
print("Aligned:", expr_98320_clinical_final.shape[1], "samples")

Samples in expression matrix: 732
Samples in metadata: 732
Common samples: 732
Aligned: 732 samples

In [57]:
clinical_98320_final = meta_98320_clinical[CLINICAL_COLS].copy()
for col in CLINICAL_COLS:
    clinical_98320_final[col] = pd.to_numeric(clinical_98320_final[col], errors="coerce")

print("Clinical feature table shape:", clinical_98320_final.shape)
print("\nMissingness per column (out of 732):")
print(clinical_98320_final.isna().sum())
print("\nMissingness %:")
print((clinical_98320_final.isna().sum() / len(clinical_98320_final) * 100).round(1))

Clinical feature table shape: (732, 11)

Missingness per column (out of 732):
g      21
cg     26
i      15
ci     27
t      16
ct     27
v      54
cv     86
ah     43
ptc    26
c4d    50
dtype: int64

Missingness %:
g       2.9
cg      3.6
i       2.0
ci      3.7
t       2.2
ct      3.7
v       7.4
cv     11.7
ah      5.9
ptc     3.6
c4d     6.8
dtype: float64

In [58]:
complete_rows = clinical_98320_final.dropna()
print(f"Samples with fully complete clinical data: {len(complete_rows)} out of {len(clinical_98320_final)}")

# Check class balance is preserved after dropping
complete_labels = meta_98320_clinical.loc[complete_rows.index, "rejection_class"]
print("\nClass distribution if we drop incomplete rows:")
print(complete_labels.value_counts())

Samples with fully complete clinical data: 568 out of 732

Class distribution if we drop incomplete rows:
rejection_class
NR       373
ABMR     128
TCMR      48
Mixed     19
Name: count, dtype: int64

In [59]:
CLINICAL_COLS_MEDIAN = clinical_98320_final.median()

clinical_98320_imputed = clinical_98320_final.copy()
was_imputed = clinical_98320_final.isna().any(axis=1).astype(int)

for col in CLINICAL_COLS:
    clinical_98320_imputed[col] = clinical_98320_imputed[col].fillna(CLINICAL_COLS_MEDIAN[col])

clinical_98320_imputed["was_imputed"] = was_imputed

print("Imputed clinical table shape:", clinical_98320_imputed.shape)
print(f"Rows with at least one imputed value: {was_imputed.sum()} out of {len(was_imputed)}")
print(clinical_98320_imputed.isna().sum().sum(), "remaining NaNs (should be 0)")

Imputed clinical table shape: (732, 12)
Rows with at least one imputed value: 164 out of 732
0 remaining NaNs (should be 0)

In [60]:
multimodal_dataset = expr_98320_clinical_final.T  # samples x genes (732 samples, all of them now)
multimodal_dataset = multimodal_dataset.join(clinical_98320_imputed)  # clinical cols + was_imputed flag
multimodal_dataset = multimodal_dataset.join(meta_98320_clinical[["rejection_class"]])

print("Multimodal dataset shape (samples x [genes + clinical + was_imputed + label]):", multimodal_dataset.shape)
print("\nClass distribution:")
print(multimodal_dataset["rejection_class"].value_counts())
print("\nImputed vs. complete breakdown:")
print(multimodal_dataset["was_imputed"].value_counts())

# Save
multimodal_dataset.to_parquet(os.path.join(PROCESSED_DIR, "GSE98320_multimodal.parquet"))
multimodal_dataset.to_csv(os.path.join(PROCESSED_DIR, "GSE98320_multimodal.csv"))

print("\nSaved GSE98320_multimodal.parquet and .csv")

Multimodal dataset shape (samples x [genes + clinical + was_imputed + label]): (732, 20098)

Class distribution:
rejection_class
NR       466
ABMR     173
TCMR      67
Mixed     26
Name: count, dtype: int64

Imputed vs. complete breakdown:
was_imputed
0    568
1    164
Name: count, dtype: int64

Saved GSE98320_multimodal.parquet and .csv

In [61]:
import shutil

shutil.make_archive("/kaggle/working/kidney_datasets", "zip", PROCESSED_DIR)
print("Created zip:", "/kaggle/working/kidney_datasets.zip")
print("Size (MB):", os.path.getsize("/kaggle/working/kidney_datasets.zip") / (1024*1024))

Created zip: /kaggle/working/kidney_datasets.zip
Size (MB): 591.2321338653564